### ISSUE TITLE
Re-create service publication documents as Metanorma documents using data

### ISSUE THREAD

**Issue by ronaldtse** [ituob/service-publications-docs#1]
Each of these documents need to be re-created as Metnaomra adoc files.

All the data have already been moved to YAML, we need to use yaml2text to re-create these documents.

* ~~1000-SR.1~~
* ~~1001-T.35B~~
* ~~1002-T.35~~
* ~~1015-E.164B~~
* ~~1060-M.1400~~
* ~~1109-Q.708B~~
* ~~1114-E.164D~~
* ~~1117-E.212A~~ ~~(pending: ru, zh, ar)~~
* ~~1125-E.218~~ ~~(pending: ru, zh, ar)~~
* ~~1125-Q.708A~~ ~~(pending: ru, zh, ar)~~
* ~~1154-RR.25.1~~
* ~~1161-E.118~~ ~~(pending other languages)~~
* ~~1162-E.212~~
* ~~669-F.1~~
* ~~955-E.180~~
* ~~974-F.400~~
* ~~976-X.121A~~
* ~~977-X.121B~~
* ~~978-F.68~~
* ~~980-F.32~~
* ~~991-PP.RES.21.pp~~
* ~~994-E.164C~~

Each of these should probably be a new task.

**Comment by manuelfuenmayor** [comment]
Working on 1000-SR.1

**Comment by manuelfuenmayor** [comment]
First doc, 1000-SR.1, is merged to master. I will follow with the rest in another PR.

**Comment by manuelfuenmayor** [comment]
@ronaldtse,

Apparently there is no adoc file in https://github.com/ituob/service-publications-data for these documents:
* 1015-E.164B
* 1060-M.1400
*  1109-Q.708B
*  1114-E.164D
*  1117-E.212A
*  1125-E.218
*  1125-Q.708A
*  1161-E.118
* 1162-E.212
* 994-E.164C

**Comment by ronaldtse** [comment]
@manuel489 correct, they need to be created according to the data we have now in the YAML.

**Comment by manuelfuenmayor** [comment]
@ronaldtse, there are documents that are written in these additional languages: Russian, Chinese, and Arabic. 
Should we include them along with French, English and Spanish?

**Comment by ronaldtse** [comment]
@manuel489 yes, we should include all of them. Which ones are still pending? Thanks!

**Comment by manuelfuenmayor** [comment]
> @manuel489 yes, we should include all of them. Which ones are still pending? Thanks!

I have added the pending languages 👍 
I'm still working on the other documents.

**Comment by ronaldtse** [comment]
@manuel489 how many documents to go? Only 1015 and 955 left? Thanks!

**Comment by manuelfuenmayor** [comment]
@ronaldtse, sorry I am so far behind on this task.

The remaining documents are:
* ~~1015-E.164B (the provided yaml file is incorrect so I'm creating a new one.)~~
* ~~955-E.180 (there are missing data in provided yaml file that I need to complete.)~~
* 1154-RR.25.1 (this one looks complex so I'm putting it last.)

I'm prioritizing to finish asap.
Thanks!

**Comment by manuelfuenmayor** [comment]
@ronaldtse, I'm not sure how to procede with 1145-RR.25.1
Provided YAML files contain mostly regex patterns.
For example, in the case of [Belgium](https://github.com/ituob/service-publications-data/blob/master/1154-RR.25.1/belgium.yaml) yaml file contains:

````
groups:
  amateur:

    - name: Automatic stations
      regex: ON0[:upper:]{2,3}

    - name: Class 2 stations
      regex: ON1[:upper:]{2,3}

    - name: Currently not in use
      regex: ON2[:upper:]{2,3}

    - name: Class 3 stations
      regex: ON3[:upper:]{2,3}

    - name: Class 1 stations
      regex: ON[4-8][:upper:]{2,3}

    - name: Class 3 stations for foreigners
      regex: ON9A[:upper:]{2}

    - name: Class 2 stations for foreigners
      regex: ON9B[:upper:]{2}

...
````

But the document taken from [original sources](https://www.itu.int/pub/T-SP-RR.25.1-2018) is:
![Capture](https://user-images.githubusercontent.com/33627611/117695666-7917b000-b18e-11eb-82e4-fc88d05091bd.PNG)

Maybe these files serve as a resource for creating another YAML file?

**Comment by ronaldtse** [comment]
@manuel489 good idea -- we can generate another YAML file with the expanded ranges. I wonder if there are existing methods to do so in Ruby...?

**Comment by manuelfuenmayor** [comment]
> I wonder if there are existing methods to do so in Ruby...?

Not sure at the moment, I'll investigate. But I'm considering creating the YAML file directly from the original PDFs.

**Comment by ronaldtse** [comment]
> But I'm considering creating the YAML file directly from the original PDFs.

@manuel489 please don't do this. We've already spent countless hours in generalising in this syntax and the data, and the data is correct. I don't think we need to expand the ranges. The goal is to be "succinct" and exact with the pattern so that it is machine-readable.

> I wonder if there are existing methods to do so in Ruby...?

To answer myself, the answer is no.

We can transform them in this way using liquid:

```
regex: OE[:amateur_area:][:upper:]{2,3}
```

=>

```
{% assign regex = "OE[:amateur_area:][:upper:]{2,3}" %}
{% assign instances = regex | replace: "{", "(" | replace: "}", " characters)" %}
{% assign upcase = instances | replace: "[:upper:]", "[A-Z]" %}
{% assign codelists = upcase | replace: "[:", "[codelist values from: " | replace: ":]", "]" %}
```

=> "ON9A[codelist values from: amateur_area][A-Z](2,3 characters)"

**Comment by manuelfuenmayor** [comment]
@ronaldtse, the thing is, I don't see how I can "re-create" the original documents in a reliable way by taking your approach.

In the case of Austria, which is the country you took as example, original text is:

![Capture1](https://user-images.githubusercontent.com/33627611/117847489-61086500-b250-11eb-975b-ce3814aa1ffb.PNG)

by taking your approach, I suppose liquid code would be something like:

````
=== Austria

[yaml2text,austria.yaml,file]
----
{% assign amateur_regex = file.groups.amateur.regex %}
{% assign amateur_instances = amateur_regex | replace: "{", "(" | replace: "}", " characters)" %}
{% assign amateur_upcase = amateur_instances | replace: "[:upper:]", "[A-Z]" %}
{% assign amateur_codelists = amateur_upcase | replace: "[:", "[codelist values from: " | replace: ":]", "]" %}

{% assign experimental_regex = file.groups.experimental.regex %}
{% assign experimental_instances = experimental_regex | replace: "{", "(" | replace: "}", " characters)" %}
{% assign experimental_upcase = experimental_instances | replace: "[:upper:]", "[A-Z]" %}
{% assign experimental_codelists = experimental_upcase | replace: "[:", "[codelist values from: " | replace: ":]", "]" %}

Amateur stations:: {{ amateur_codelists }}

Experimental stations:: {{ experimental_codelists }}

Digits indicating the provinces or areas::: 
+
--
{% for codelist in file.codelists.amateur_area %}
{{ codelist[0] }} -- {{ codelist[1] }} +
{% endfor %}
--
----
````

giving the output:

![Capture2](https://user-images.githubusercontent.com/33627611/117847516-682f7300-b250-11eb-9498-5b3a1df6be8d.PNG)

This is quite different to text shown in original document.
(Surely I'm misunderstanding something, but don't know what exactly.)

**Comment by ronaldtse** [comment]
@manuel489 yeah being a bit different is acceptable for now. Thanks 😉

**Comment by manuelfuenmayor** [comment]
@ronaldtse, I draw your attention to: ~~https://github.com/metanorma/metanorma-standoc/issues/469~~ (moved to https://github.com/metanorma/metanorma-plugin-datastruct/issues/11)
It seems like [repeated nodes objects](https://yaml.org/spec/1.2/spec.html#id2760395) aren't supported in yaml2text blocks.

**Comment by manuelfuenmayor** [comment]
There are many YAML files that contain repeated nodes.
In such case, I could edit them (for example) from:

````
groups:
  amateur: &general
    regex: O[F-J][:digit:][0-9A-Z]{3}[:upper:]{1}

  experimental: *general
````
To:

````
  groups:
  amateur: 
    regex: O[F-J][:digit:][0-9A-Z]{3}[:upper:]{1}

  experimental: 
    regex: O[F-J][:digit:][0-9A-Z]{3}[:upper:]{1}
````
