### ISSUE TITLE
Develop the "dataset change action" data structure

### ISSUE THREAD

**Issue by ronaldtse** [ituob/service-publications-docs#51]
This task was from [#47](https://github.com/ituob/service-publications-docs/issues/47#issuecomment-2875689068):

> create a diff “change” structure to store OB issue changes. 

The "dataset change object" structure described in the [README](https://github.com/ituob/service-publications-docs#dataset-change-object) is just a draft and is **not finalized**.

We now have a new approach here:
* https://github.com/ituob/service-publications-docs/pull/49

The sample output is:

```yaml
# - _class: E118Amendment
#  actions:
  - action_type: ADD
    position: '42'
    entry:
      country_or_area:
        en: Portugal
      company_name: Telecomunicações Moveis Nacionais
      company_address_1: Av.Alvaro País No 2
      company_address_2: 1649-041 LISBOA
      company_address_3: Portugal
      contact: Mr José Paulo Pires
      contact_address_1: Telecomunicações Moveis Nacionais
      contact_address_2: Av.Alvaro País No 2
      contact_address_3: 1649-041 LISBOA
      contact_address_4: Portugal
      tel:
      - "+351 21 782 4248"
      fax:
      - "+351 21 791 4500"
      email:
      - jose-pires@telecom.pt
      issue_id_number: 89 351 80
      effective_date: 1.II.2012
``` 

Clearly, we are missing some "OB-level metadata", such as the OB issue, some unique identifier, the "date position" the patch acts on, etc.

The task is to be done to allow us to render the OB issues from a set of dataset patches.
