### ISSUE TITLE
Parsing OldIssue: F32_TDI messages not fully parsed

### ISSUE THREAD

**Issue by ronaldtse** [ituob/service-publications-docs#54]
```
cd scripts
bundle
bundle exec ./parse_issue.rb F32_TDI 1013
```

Output:
```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Issue 1013:
---
_class: F32TDIAmendment
position_on: '2011-04-15'
actions:
- entries:
  - country_or_area:
      en: MALAYSIA
      fr: MALAISIE
      es: MALASIA
    network_roa: TMB – Telekom Malaysia Berhad,
    network_code: MA-
    office_code: MAAS
    subarea:
      en: ALOR STAR
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

Original data:
```yaml
  - type: amendment
    target:
      publication: E164_ACN
    contents:
      en:
        type: doc
        content:
          - type: table
            content:
              - type: table_row
                content:
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            marks:
                              - type: em
                            text: Country/geographical area
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            marks:
                              - type: em
                            text: E.164 Country Code
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            marks:
                              - type: em
                            text: 'Mobile telephone numbers, first digits after'
                          - type: hard_break
                            marks:
                              - type: em
                          - type: text
                            marks:
                              - type: em
                            text: country code
          - type: paragraph
            content:
              - type: text
                text: "\_"
          - type: paragraph
            content:
              - type: text
                marks:
                  - type: strong
                text: "P\_ 7\_ French Polynesia (Territoire français d'outre-mer)\_\_\_\_ LIR"
          - type: table
            content:
              - type: table_row
                content:
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            text: French Polynesia (Territoire français d'outre-mer)
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            text: '689'
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            text: '2,3,7'
          - type: paragraph
            content:
              - type: text
                text: "\_"
          - type: paragraph
            content:
              - type: text
                marks:
                  - type: strong
                text: "P\_ 5\_ Iceland\_\_\_\_ LIR"
          - type: table
            content:
              - type: table_row
                content:
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            text: Iceland
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            text: '354'
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            text: '385, 388, 389, 61-69, 77, 780-783, 82-89, 954, 958'
  - type: amendment
    target:
      publication: E212_MNC
    contents:
      en:
        type: doc
        content:
          - type: paragraph
            content:
              - type: text
                marks:
                  - type: strong
                text: "P \_19\_ Israel\_ ADD"
          - type: paragraph
            content:
              - type: text
                text: "\_"
          - type: table
            content:
              - type: table_row
                content:
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            marks:
                              - type: em
                            text: Country/geographical area
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            marks:
                              - type: em
                            text: MCC + MNC*
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            marks:
                              - type: em
                            text: Name of Operator/Network
              - type: table_row
                content:
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            text: Israel
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            text: 425 18
                          - type: hard_break
                          - type: text
                            text: 425 20
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            text: "Cellact Communications\_ Ltd (MVNO)"
                          - type: hard_break
                          - type: text
                            text: Bezeq Ltd
          - type: paragraph
            content:
              - type: text
                text: "\_"
          - type: paragraph
            content:
              - type: text
                marks:
                  - type: strong
                text: "P \_31\_ Switzerland\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ SUP"
          - type: paragraph
            content:
              - type: text
                text: "\_"
          - type: table
            content:
              - type: table_row
                content:
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            marks:
                              - type: em
                            text: Country/geographical area
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            marks:
                              - type: em
                            text: MCC + MNC*
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            marks:
                              - type: em
                            text: Name of Operator/Network
              - type: table_row
                content:
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            text: Switzerland
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            text: 228 07
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            text: In & Phone S.A.
          - type: paragraph
            content:
              - type: text
                text: "\_"
          - type: paragraph
            content:
              - type: text
                text: ____________
          - type: paragraph
            content:
              - type: text
                text: "*\_\_\_\_ MCC: Mobile Country Code / Indicatif de pays du mobile / Indicativo de país para el servicio móvil."
          - type: paragraph
            content:
              - type: text
                text: "**\_\_ MNC: Mobile Network Code / Code de réseau mobile / Indicativo de red para el servicio móvil."
  - type: amendment
    target:
      publication: F32_TDI
      position_on: 2011-4-15
    contents:
      en:
        type: doc
        content:
          - type: paragraph
            content:
              - type: text
                marks:
                  - type: strong
                text: "P \_27 \_\_\_MALAYSIA"
          - type: paragraph
            content:
              - type: text
                text: "Network code: MA\_\_\_\_\_"
              - type: text
                marks:
                  - type: strong
                text: "COL\_\_"
              - type: text
                text: '2'
              - type: text
                marks:
                  - type: em
                text: "\_\_\_"
              - type: text
                marks:
                  - type: em
                  - type: strong
                text: 'TMB – Telekom Malaysia Berhad, Kuala Lumpur'
          - type: paragraph
            content:
              - type: text
                marks:
                  - type: strong
                text: "COL\_\_1-5\_\_\_\_\_SUP"
          - type: paragraph
            content:
              - type: text
                marks:
                  - type: em
                text: 'Date of application: 1 July 2012'
          - type: paragraph
            content:
              - type: text
                text: "\_"
          - type: table
            content:
              - type: table_row
                content:
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            marks:
                              - type: em
                            text: Country/ geographical area
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            marks:
                              - type: em
                            text: Network (administration/ROA)
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            marks:
                              - type: em
                            text: Network code
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            marks:
                              - type: em
                            text: Name of
                          - type: hard_break
                            marks:
                              - type: em
                          - type: text
                            marks:
                              - type: em
                            text: Telegraph Office
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            marks:
                              - type: em
                            text: Office code
              - type: table_row
                content:
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            marks:
                              - type: em
                            text: '1'
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            marks:
                              - type: em
                            text: '2'
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            marks:
                              - type: em
                            text: '3'
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            marks:
                              - type: em
                            text: '4'
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            marks:
                              - type: em
                            text: '5'
              - type: table_row
                content:
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            text: MALAISIE
                      - type: paragraph
                        content:
                          - type: text
                            text: MALAYSIA
                      - type: paragraph
                        content:
                          - type: text
                            text: MALASIA
                      - type: paragraph
                        content:
                          - type: text
                            text: "\_"
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            text: 'TMB – Telekom Malaysia Berhad,'
                      - type: paragraph
                        content:
                          - type: text
                            text: Kuala Lumpur
                      - type: paragraph
                        content:
                          - type: text
                            text: "\_"
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            text: MA-
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            text: ALOR STAR
                      - type: paragraph
                        content:
                          - type: text
                            text: IPOH
                      - type: paragraph
                        content:
                          - type: text
                            text: JOHORE BAHRU
                      - type: paragraph
                        content:
                          - type: text
                            text: Kluang
                      - type: paragraph
                        content:
                          - type: text
                            text: KOTA BHARU KELANTAN
                      - type: paragraph
                        content:
                          - type: text
                            text: KOTA KINABALU
                      - type: paragraph
                        content:
                          - type: text
                            text: KUALA LUMPUR
                      - type: paragraph
                        content:
                          - type: text
                            text: KUALA TRENGGANU
                      - type: paragraph
                        content:
                          - type: text
                            text: KUANTAN
                      - type: paragraph
                        content:
                          - type: text
                            text: KUCHING
                      - type: paragraph
                        content:
                          - type: text
                            text: MALACCA
                      - type: paragraph
                        content:
                          - type: text
                            text: Pelabuhan Kelang
                      - type: paragraph
                        content:
                          - type: text
                            text: PENANG
                      - type: paragraph
                        content:
                          - type: text
                            text: PETALING JAYA
                      - type: paragraph
                        content:
                          - type: text
                            text: SEREMBAN
                      - type: paragraph
                        content:
                          - type: text
                            text: Taiping
                      - type: paragraph
                        content:
                          - type: text
                            text: All others
                  - type: table_cell
                    attrs:
                      colspan: 1
                      rowspan: 1
                      colwidth: null
                    content:
                      - type: paragraph
                        content:
                          - type: text
                            text: MAAS
                      - type: paragraph
                        content:
                          - type: text
                            text: MAIP
                      - type: paragraph
                        content:
                          - type: text
                            text: MAJB
                      - type: paragraph
                        content:
                          - type: text
                            text: MAKU
                      - type: paragraph
                        content:
                          - type: text
                            text: MAKO
                      - type: paragraph
                        content:
                          - type: text
                            text: MAKB
                      - type: paragraph
                        content:
                          - type: text
                            text: MAKL
                      - type: paragraph
                        content:
                          - type: text
                            text: MATG
                      - type: paragraph
                        content:
                          - type: text
                            text: MAKN
                      - type: paragraph
                        content:
                          - type: text
                            text: MAKG
                      - type: paragraph
                        content:
                          - type: text
                            text: MAMC
                      - type: paragraph
                        content:
                          - type: text
                            text: MAPK
                      - type: paragraph
                        content:
                          - type: text
                            text: MAPG
                      - type: paragraph
                        content:
                          - type: text
                            text: MAPJ
                      - type: paragraph
                        content:
                          - type: text
                            text: MASR
                      - type: paragraph
                        content:
                          - type: text
                            text: MATP
                      - type: paragraph
                        content:
                          - type: text
                            text: MAMX
          - type: paragraph
            content:
              - type: text
                text: "\_"
          - type: paragraph
            content:
              - type: text
                text: ____________
          - type: paragraph
            content:
              - type: text
                text: "*\_\_\_\_\_\_\_\_ See Note published in present ITU Operational Bulletin No. 1013 of 1.X.2012, page 5 ."
```
